version: '3'
services:
  app:
    image: hoangluong202/cep-be
    env_file:
      - .env
    restart: always
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - '3003:3003'

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      TZ: 'GMT'
      PGTZ: 'GMT'
    ports:
      - '5432:5432'
    volumes:
      - ./db-data/postgresql:/var/lib/postgresql/data
    env_file:
      - .env
