name: 'cep-be'
services:
  app:
    image: hoangluong202/cep-be
    env_file:
      - .env
    volumes:
      - ./secrets/cert.key:/usr/src/app/secrets/cert.key:ro
      - ./secrets/cert.crt:/usr/src/app/secrets/cert.crt:ro
    restart: always
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - '3003:3003'

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      TZ: 'GMT'
      PGTZ: 'GMT'
    ports:
      - '5432:5432'
    volumes:
      - ./db-data/postgresql:/var/lib/postgresql/data
    env_file:
      - .env
  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8080:8080"
    restart: always